name: Deploy to Tencent Cloud

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # 安装 Node.js (移到 clear 之前)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'npm'

      # 安装依赖 (在工作流中)
      - name: Install Dependencies
        run: npm install

      # 构建 VuePress 站点 (在工作流中)
      - name: Build VuePress Site
        run: npm run build

      # 部署到腾讯云
      - name: Deploy to Tencent Cloud
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: emptydust
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: "bash /home/emptydust/deploy.sh"
