name: Deploy to Tencent Cloud

on:
  push:
    branches:
      - main  # 触发 workflow 的分支

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Tencent Cloud
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}  # 使用 Secret 存储 IP 地址
          username: emptydust
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            ssh -o StrictHostKeyChecking=no emptydust@${{ secrets.SERVER_IP }} "bash /home/emptydust/deploy.sh"
