name: Deploy to Tencent Cloud

on:
  push:
    branches:
      - main  # 触发 workflow 的分支

# 添加权限声明
permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # 添加清空工作目录的步骤
      - name: 清空工作目录
        run: rm -rf *
        shell: bash

      # 安装 Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'  # 或者你需要的 Node.js 版本
          cache: 'npm'  # 缓存 npm 依赖

      - name: Deploy to Tencent Cloud
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}  # 使用 Secret 存储 IP 地址
          username: emptydust
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: "bash /home/emptydust/deploy.sh"
